version: '3.9'

services:
  s_nginx:
    container_name: c_nginx
    image: nginx
    volumes:
      - ./website:/usr/share/nginx/html 
    ports:
      - 8080:80
      - 8081:80

  s_html:
    container_name: c_html
    image: httpd
    volumes:
      - ./website:/usr/local/apache2/htdocs/ 
    ports:
      - 9090:80
      - 9091:80

volumes:
  html:

